name: CI

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master, test]

jobs:
  ci:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]  # macos, hangs at present
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', 'pypy3']
        exclude:
          - os: windows
            python-version: pypy3
    steps:
      - if: ${{ matrix.os == 'ubuntu' }}
        run: sudo apt-get install strace
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -U pip wheel setuptools
      - run: |
          pip install .
          pip install -r dev_requirements.txt python-coveralls
      - run: pip freeze
      - run: doit pyflakes
      - run: py.test -vv
        env:
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSIOENCODING: utf-8
      - if: ${{ matrix.os == 'ubuntu' && matrix.python-version == '3.8' }}
        run: |
          doit coverage
          coveralls || echo "TODO: remove when run on a repo that is set up"
